<?xml version="1.0" encoding="utf-8"?><Database Name="contacts" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.20.100.162,64684\sqlexpress;Initial Catalog=contacts;User ID=sa" SettingsObjectName="Contacts.Properties.Settings" SettingsPropertyName="contactsConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.contact" Member="contact">
    <Type Name="contact">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>